//union literals 
var num;
num = 66;
console.log(num);
num = "malaika";
console.log(num);
num = true;
console.log(num);
var num1;
num1 = "i love chocolate";
console.log(num1);
num1 = [1, 2, 3, 4, 5, 6, 7, 8, 9, 0];
console.log(num1);
num1 = [true, false];
console.log(num1);
var num2 = "hello world";
num2 = 33;
console.log(num2);
var num3 = true;
console.log(num3);
num3 = 22;
console.log(num3);
