"use strict";
let num1 = 5;
let num2 = 9;
console.log(num1 + num2);
let num3 = 6;
let num4 = 4;
console.log(num3 + num4 + 9);
let num5 = 7 + 7;
num5 += 5;
console.log(num5);
const name1 = "Malaika";
const name2 = " zahid ";
const sum1 = name1 + name2;
console.log(sum1);
let num6 = 6 + 7;
num6++;
console.log(num6);
let num12 = 5;
let num13 = 7;
num12 = 4;
console.log(num12 + num13);
const num14 = 6 + 6 + 7 + 8;
console.log(num14);
let a = 4;
let b = 6;
console.log(a - b);
let c = 8;
let d = 4;
console.log(c - d);
let E = 10 - 8;
E--;
console.log(E);
let f = 7 - 3;
console.log(f);
let G = 9 - 2;
G -= 3;
console.log(G);
const num7 = 8;
const num8 = 7;
console.log(num7 * num8);
let num9 = 9 * 9;
console.log(num9);
let num10 = 7 * 5;
num10 *= 2;
console.log(num10);
const num11 = 6 * 6;
console.log(num11);
let num15 = 6;
let num17 = 7;
num17 = 2;
console.log(num15 * num17);
let num18 = 75;
let num19 = 8;
console.log(num18 / num19);
const H = 12 / 6;
console.log(H);
let i = 2 / 6;
i /= 4;
console.log(i);
let j = 25;
let k = 2;
k = 9;
console.log(j / k);
let l = 24 / 2;
console.log(l);
let M = 3;
let n = 6;
console.log(M % n);
let o = 5 % 7;
console.log(o);
let p = 3 % 9;
p %= 5;
console.log(p);
const Q = 56 % 7;
console.log(Q);
let R = 6;
let s = 4;
R = 5;
console.log(R % s);
let t = 6;
let u = 6;
console.log(t ** u);
let v = 2 ** 2;
console.log(v);
let w = 3 ** 3;
console.log(w);
let x = 7 ** 2;
x = 4 ** 2;
console.log(x);
const y = 3 ** 2;
console.log(y);
let z = 5 ** 2;
console.log(z);
//comparison operator
console.log(6 == 6);
console.log(6 == 6);
console.log(8 == 8);
console.log(3 == 3);
console.log(7 == 7);
console.log(5 != 5);
console.log(4 != 4);
console.log(3 != 3);
console.log(1 != 1);
console.log(7 != 7);
console.log(5 < 8);
console.log(9 < 5);
console.log(4 < 6);
console.log(6 < 6);
console.log(7 < 1);
console.log(6 > 7);
console.log(4 > 4);
console.log(8 > 6);
console.log(7 > 5);
console.log(9 > 2);
console.log(4 <= 6);
console.log(4 >= 2);
console.log(7 >= 9);
console.log(9 >= 10);
console.log(6 >= 4);
console.log(5 > 5);
console.log(7 < 6);
