var cars = ["dodge", "lambo", "la farrari"];
cars.unshift("land cruiser");
console.log(cars);
//console.log (cars[2])
var city = ["karachi", "multan", "peshawar", "lahore", "islamabad"];
city.push("hyderabad");
city.shift();
console.log(city);
var friends = ["samra", "laiba", "nashra", "ramsha",];
friends.push("kinza", "ramish", "rumaisa", "arshiya");
friends.pop();
console.log(friends);
var students = ["areeba", "mano", "halima", "hamza", "ali"];
students.push("mustafa", "rumaisa");
students.unshift("areeqa", "sumaiya");
console.log(students);
var recipe = ["salt", "sugar", "milk", "water", "tea bag", "cinnamon"];
recipe.pop();
recipe.shift();
console.log(recipe);
var accessories = ["earings", "scrunchies", "watch", "hairband", "bow", "necklace", "rings",];
var new1 = accessories.slice(3, 7);
console.log(accessories, new1);
var countries = ["pakistan", "dubai", "europe", "kuwait", "USA", "qatar", "iran"];
var country = countries.slice(2, 5);
console.log(countries, country);
var colours = ["pink", "blue", "purple", "black", "brown", "red"];
colours.splice(2, 2, "green", "yellow");
console.log(colours);
var fruits = ["apple", "mango", "orange", "grapes"];
fruits.splice(0, 1, "kiwi", "cherry");
console.log(fruits);
